[package]
name = "wayland-dimmer-overlay"
version = "0.1.0"
edition = "2021"

[dependencies]
smithay-client-toolkit = "0.18"
wayland-client = "0.31"
wayland-protocols-wlr = { version = "0.2", features = ["client"] }